language: python
sudo: false
dist: trusty

matrix:
  include:
    - python: 3.6
      env: CHECK_DOCS=1
    - python: 3.6
      env: CHECK_FORMATTING=1
    # The pypy tests are slow, so we list them first
    - python: pypy3.5
    - language: generic
      env: USE_PYPY_NIGHTLY=1
    - python: 3.5.0
    - python: 3.5.2
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.5-dev
    - python: 3.6-dev
    - python: 3.7-dev
      dist: xenial
      sudo: required
    - python: 3.8-dev
      dist: xenial
      sudo: required

script:
  - ci/travis.sh
