os: linux
language: python
dist: focal

jobs:
  include:
    - python: 3.6.1  # earliest 3.6 version available on Travis
      # https://github.com/pypa/setuptools/issues/2350
      env: SETUPTOOLS_USE_DISTUTILS=stdlib
      dist: bionic

script:
  - ./ci.sh

branches:
  except:
    - /^dependabot/.*/
